services:
  traefik:
    image: "traefik:v2.11"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


  alertmanager:
    image: "prom/alertmanager"
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alertmanager.rule=Host(`alertmanager.localhost`)"
      - "traefik.http.routers.alertmanager.entrypoints=web"

  hook:
    image: coveros/webhook-tester
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hook.rule=Host(`alertmanager.localhost`)"
      - "traefik.http.routers.hook.entrypoints=web"
      - "traefik.http.services.hook.loadbalancer.server.port=8080"

  grafana:
    image: "grafana/grafana"
    depends_on:
      - prometheus
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "./provisioning:/etc/grafana/provisioning"
      - "./dashboards:/etc/dashboards"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`)"
      - "traefik.http.routers.grafana.entrypoints=web"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090"
    volumes:
      - "./prometheus:/etc/prometheus"
      - "prometheus_data:/prometheus_data"
      - "./prometheus/alert_rules:/etc/prometheus/alert_rules"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.localhost`)"
      - "traefik.http.routers.prometheus.entrypoints=web"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

volumes:
  prometheus_data:
  grafana_data: 
