global:
  scrape_interval:     15s 
  evaluation_interval: 15s 
  external_labels:
      monitor: 'example'
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']
rule_files:
  - '/etc/prometheus/alert_rules/*.yml'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: node
    static_configs:
      - targets: ['10.0.0.7:9100']
      - targets: ['10.0.0.5:9100']
      - targets: ['10.0.0.4:9100']
      - targets: ['10.0.0.3:9100']
      - targets: ['10.0.0.2:9100']
