version: "3.3"
services:
  traefik:
    image: "traefik:v2.10"
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

      - "--certificatesresolvers.myresolver.acme.email=nr@formitas.com"
      - "--providers.file.filename=/etc/traefik/dynamic/config.yml"
      - "--providers.file.watch=true"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
      - "/opt/traefik/dynamic:/etc/traefik/dynamic"

