version: "3.3"
services:
  traefik:
    image: "traefik:v2.11"
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.email=nr@formitas.com"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
  
  grafana:
    image: "grafana/grafana"
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "./provisioning:/etc/grafana/provisioning"
      - "./dashboards:/etc/dashboards"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

      - "traefik.http.routers.grafana.rule=Host(`grafana.qubedoo.com`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.middlewares.auth.basicauth.users=formitas:$$2y$$05$$I42xs7Q.dz/VcXHjMSo6A.ORWaSiomF6ekuq2u1Foxn3Pm37bDUue" 
      - "traefik.http.routers.grafana.middlewares=auth@docker"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "./prometheus:/etc/prometheus"
      - "prometheus_data:/prometheus_data"
      - "./prometheus/alert_rules:/etc/prometheus/alert_rules"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

      - "traefik.http.routers.prometheus.rule=Host(`prometheus.qubedoo.com`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.tls.certresolver=myresolver"
      - "traefik.http.middlewares.auth.basicauth.users=formitas:$$2y$$05$$I42xs7Q.dz/VcXHjMSo6A.ORWaSiomF6ekuq2u1Foxn3Pm37bDUue" 
      - "traefik.http.routers.prometheus.middlewares=auth@docker"

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    restart: always
    labels:
      - "traefik.enable=true"
      # no loadbalancer will handle the route. this is declared in the alertmanager.yml conf
      - "traefik.http.routers.alertmanager.rule=Host(`alertmanager.qubedoo.com`)"
      - "traefik.http.routers.alertmanager.entrypoints=websecure"
      - "traefik.http.routers.alertmanager.tls=true"
      - "traefik.http.routers.alertmanager.tls.certresolver=myresolver"
      - "traefik.http.middlewares.auth.basicauth.users=formitas:$$2y$$05$$I42xs7Q.dz/VcXHjMSo6A.ORWaSiomF6ekuq2u1Foxn3Pm37bDUue" 
      - "traefik.http.routers.alertmanager.middlewares=auth@docker"

  hook:
    image: coveros/webhook-tester
    container_name: webhook_tester
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.hook.loadbalancer.server.port=8080"

      - "traefik.http.routers.hook.rule=Host(`alertmanager.qubedoo.com`)"
      - "traefik.http.routers.hook.entrypoints=websecure"
      - "traefik.http.routers.hook.tls=true"
      - "traefik.http.routers.hook.tls.certresolver=myresolver"

volumes:
  prometheus_data:
  grafana_data:
