---
name: Grafana and Prometheus Deployment

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Formitas registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: formitas-ag
          password: ${{ secrets.ACTIONS_KEY }}

      - name: Pull Docker Image
        run: docker pull ghcr.io/qubedoo/deployment-config:main

      - name: Create files
        run: |
          mkdir -p secrets/ansible-vault secrets/.ssh
          echo "${{ secrets.SSH_KEY }}" > secrets/.ssh/id_server
          echo "${{ env.KNOWN_HOSTS }}" > secrets/.ssh/known_hosts

      - name: run ansible-playbook
        run: |
          docker run \
          -v $PWD:/deploy ghcr.io/qubedoo/deployment-config:main \
          ash -c \
          'cd /deploy; \ 
          ansible-playbook --private-key=secrets/.ssh/id_server \
          -i inventories/inventory.ini \
          install.yml'


